package org.openmrs.module.ihshr.pull;

public enum ShrPullErrorCode {
	PATIENT_NOT_FOUND, PATIENT_NOT_SYNCED, INVALID_FILTER, SHR_UPSTREAM_ERROR, SHR_AMBIGUOUS_PATIENT, SHR_TIMEOUT, UNAUTHORIZED_PAGE_URL, FORBIDDEN, UNAUTHORIZED
}
